### ISSUE TITLE
[Bug]: Libc Access Denied 

### ISSUE THREAD

**Issue by Inazuma-Saru** [DevMoxxie/termux-monet#2]
### Problem description

![Screenshot_20220710-192852_Termux](https://user-images.githubusercontent.com/91070944/178144949-4324dddb-69d8-454a-9294-212b73075b6e.png)

libc: Access denied finding property "odsign.verification.success"

when I do termux-setup-storage or any other command sometimes this appears

### Steps to reproduce the behavior.

termux-setup-storage
termux-reload-settings
and there are some more but i forgot

### What is the expected behavior?

Hopefully it can be improved, and optimized 

### System information

* Termux Monet version: 0.118.0+334c902
* Is Nightly or Stable?: Nightly
* Android OS version: 12.1
* Device model: Realme
*

**Comment by DevMoxxie** [comment]
Weird.. This might be something with your setup i guess. Both commands have worked on my termux, with or without my setup.

Are you able to backup your termux data, reinstall the app and test without any package?

![Picsart_22-07-10_10-59-32-307](https://user-images.githubusercontent.com/103902727/178148069-9c7faeaa-4f53-4226-b627-a17c7b282870.jpg)
![Picsart_22-07-10_10-59-47-026](https://user-images.githubusercontent.com/103902727/178148070-90d38f59-0f3a-4788-8c5e-513e31c4b8ad.jpg)

**Comment by Inazuma-Saru** [comment]
oh ok it's back to normal

**Comment by Indranil012** [comment]
> Weird.. This might be something with your setup i guess. Both commands have worked on my termux, with or without my setup.
> 
> Are you able to backup your termux data, reinstall the app and test without any package?
> 
> And.. do you have installed any app like termux-api or termux-styling?
> 
> ![Picsart_22-07-10_10-59-32-307](https://user-images.githubusercontent.com/103902727/178148069-9c7faeaa-4f53-4226-b627-a17c7b282870.jpg) ![Picsart_22-07-10_10-59-47-026](https://user-images.githubusercontent.com/103902727/178148070-90d38f59-0f3a-4788-8c5e-513e31c4b8ad.jpg)

What's the name of this theme?

**Comment by HardcodedCat** [comment]
> > Weird.. This might be something with your setup i guess. Both commands have worked on my termux, with or without my setup.
> > Are you able to backup your termux data, reinstall the app and test without any package?
> > And.. do you have installed any app like termux-api or termux-styling?
> > ![Picsart_22-07-10_10-59-32-307](https://user-images.githubusercontent.com/103902727/178148069-9c7faeaa-4f53-4226-b627-a17c7b282870.jpg)
> 
> What's the name of this theme?

powerlevel10k
