### ISSUE TITLE
F-Droid Repo

### ISSUE THREAD

**Issue by rodrigoswz** [DevMoxxie/termux-monet#3]
### Feature description

Would it be possible to create a F-Droid repo to easily update Termux Monet?

### Additional information

Official Termux has updates via f-droid

**Comment by DevMoxxie** [comment]
Maybe

Soon i'll try to add it to F-Droid, i've already made a description and short description, following their guidelines.

But i'm not sure if F-Droid staff will accept it, since Termux Monet is a fork

**Comment by HardcodedCat** [comment]
Since termux-monet has been marked as debuggable, F-Droid won't accept it

So this idea was discarded

**Comment by raulvasquez** [comment]
Would the Izzy on Android repo accept?

**Comment by HardcodedCat** [comment]
I'll try, their requirements, doesn't look so strict

**Comment by TPS** [comment]
> I'll try, their requirements doesn't look so strict

@KitsunedFox What was the outcome w/ Izzy's repo?
